### ISSUE TITLE
Deploy discourse-mozilla-iam to prod

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/discourse#54]
Turning this into the meta issue:

- [x] use a 15 minute refresh: #12 
- [x] do group refresh on email-out: #13 
- [x] add sign up to log in button: #90 
- [x] refactor plugin
- [x] ensure we're getting profile data from the correct place (not `app_metadata`)
- [x] test `discourse-mozilla-iam` and `discourse-mozillians` can live together on staging
- [x] deploy `discourse-mozilla-iam` plugin in prod

**Comment by LeoMcA** [comment]
https://github.com/mozilla/discourse-mozilla-iam/pull/1#issuecomment-309107747

**Comment by hmitsch** [comment]
Does this also include:
> Make Discourse compatible with the 'cis_whitelist' group. Goal: Replace access to https://discourse.mozilla.org/c/iam/internal with Q2 OKR mechanics)

If yes, may I suggest an additional **acceptance criteria**:
* Access to https://discourse.mozilla.org/c/iam/internal is replaced with Q2 OKR mechanics
* (optional) Access to https://discourse.mozilla.org/c/mozillians/nda is replaced with Q2 OKR mechanics

**Comment by LeoMcA** [comment]
Yes, updated this issue to include:
> Access to https://discourse.mozilla.org/c/iam/internal is replaced with Q2 OKR mechanics

And created #100 to include:
> (optional) Access to https://discourse.mozilla.org/c/mozillians/nda is replaced with Q2 OKR mechanics

...as it's blocked by the full CIS rollout.
