### ISSUE TITLE
Migrate mofo's instances to discourse.mozilla.org

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/discourse#97]
Related discussion: https://github.com/MozillaFoundation/mofo-devops/issues/529
Upstream script: https://meta.discourse.org/t/topic-and-category-export-import/38930

#### Outstanding Questions

- Are we running into any TOS/Privacy Policy/Legal issues by migrating?

#### TODO

- [ ] write migration script
- [ ] work out nginx redirect rules/logic
- [ ] set up clone of discourse.mozilla.org production to test migrations

#### Current Requirements

- Migrate:
  - "Policy + Advocacy Issues" category
    - Rename to "Open Policy + Advocacy"
- Archive:
  - Nothing
- Redirect:
  - Topics

#### TODO

- [x] get approval to migrate: https://github.com/MozillaFoundation/mofo-devops/issues/529#issuecomment-324468861
- [ ] obtain admin access to instance
  - [ ] set site to read only
  - [ ] clean up spam
  - [ ] obtain database backup
- [ ] test migration script
- [ ] schedule maintenance on discourse.mozilla.org
- [ ] set instance to read only
- [ ] obtain database backup
- [ ] set discourse.mozilla.org to read only
- [ ] run migration script on discourse.mozilla.org production
- [ ] make discourse.mozilla.org writeable again
- [ ] set up nginx redirects on instance
- [ ] delete instance

#### Current Requirements

- Migrate:
  - Public Topics
- Archive:
  - All of the above
- Redirect:
  - Topics

#### TODO

- [x] get approval to migrate: https://github.com/MozillaFoundation/mofo-devops/issues/529#issuecomment-323845991
- [ ] fix ssl issue on instance
- [ ] obtain admin access to instance
  - [ ] set site to read only
  - [ ] clean up spam
  - [ ] obtain database backup
- [ ] test migration script
- [ ] schedule maintenance on discourse.mozilla.org
- [ ] set discourse.mozilla.org to read only
- [ ] run migration script
- [ ] make discourse.mozilla.org writeable again
- [ ] set up nginx redirects on instance
- [ ] delete instance

### forum.learning.mozilla.org
**We'll loop back to this after tackling the two above**

**Comment by LeoMcA** [comment]
Sprint 15 goal: finish requirements engineering
